### ISSUE TITLE
Create Domain playbook does not work in Instruqt

### ISSUE THREAD

**Issue by brianaddicks** [RedHatGov/product-demos#39] opened 2022-11-08 21:48 UTC
When using instruqt, after running setup for windows and running windows/create_ad_domain.yml, the job fails with what looks like a python dependency problem. Job output attached. To replicate:
[job_5.txt](https://github.com/RedHatGov/product-demos/files/9965511/job_5.txt)

Start instruqt session
Click through to windows section
Run setup job template with windows selected in drop down
Run "WINDOWS / AD /Create Domain" job template

**Comment by willtome** [comment] 2022-11-09 04:04
This error was do to cryptography package >38. Fixed in [PR](https://github.com/cloin/ee-builds/pull/19) for EE used in instruqt.

However, a new error is due to community.general lacking the random_string lookup plugin. This will need to be updated before closing this issue.

**Comment by willtome** [comment] 2022-11-09 16:05
Next error: Administrator account must be used to create domain otherwise reconnect after reboot fails.

**Comment by willtome** [comment] 2022-11-10 05:22
Domain installation changes enforcement of password expiration. Setting the password to never expire or rebuilding the image more often will avoid this issue. This [PR](https://github.com/ansible/instruqt/pull/262) sets the password to never expire.

The current workaround is to run this command with the WINDOWS / Run Script job before running the Create AD Domain job. 
`Set-LocalUser -Name "admin" -PasswordNeverExpires 1`

**Comment by willtome** [comment] 2022-11-10 20:34
Switched to using an instance in instruqt that does not have an expired password. That was the root cause of the issue along with the cryptography package version. Both are resolved and the ability to manage windows nodes is restored.

**Closed as completed by willtome** 2022-11-10 20:34 UTC
Labels: CRITICAL
